constexpr char g_engine_name[] = "Fiat 1.6L Tipo SCR - ASPIRADO";
constexpr double g_engine_sound_volume = 1.0;
constexpr double g_engine_radial_spacing = 4.0;
constexpr double g_engine_source_sink_volume_m3 = 1.00e20;
constexpr double g_engine_piston_diameter_m = 0.0864;
constexpr double g_engine_piston_crank_throw_length_m = 0.0337;
constexpr double g_engine_piston_connecting_rod_length_m = 0.1285;
constexpr double g_engine_piston_connecting_rod_mass_kg = 0.45;
constexpr double g_engine_piston_head_mass_density_kg_per_m3 = 9000.0;
constexpr double g_engine_piston_head_compression_height_m = 0.025;
constexpr double g_engine_piston_head_clearance_height_m = 0.003;
constexpr double g_engine_piston_dynamic_friction_n_m_s_per_r = 0.020;
constexpr double g_engine_piston_static_friction_n_m_s_per_r = 0.50;
constexpr double g_engine_gas_momentum_damping_time_constant_s = 0.90e-3;
constexpr double g_engine_eplenum_wave_pipe_length_m = 1.6;
constexpr double g_engine_mic_position_ratio = 0.1;
constexpr double g_engine_velocity_low_pass_cutoff_frequency_hz = 12000.0;
constexpr double g_engine_chamber_volume_m3 = 3.95e-4;
constexpr double g_engine_throttle_volume_m3 = 2.0e-4;
constexpr double g_engine_irunner_volume_m3 = 2.4e-4;
constexpr double g_engine_injector_volume_m3 = 7.9e-6;
constexpr double g_engine_erunner_volume_m3 = 1.0e-4;
constexpr double g_engine_eplenum_volume_m3 = 1.6e-4;
constexpr double g_engine_exhaust_volume_m3 = 3.2e-4;
constexpr double g_engine_max_flow_area_m2 = 3.8e-3;
constexpr double g_engine_source_max_flow_area_m2 = 0.00304;
constexpr double g_engine_throttle_max_flow_area_m2 = 0.00304;
constexpr double g_engine_irunner_max_flow_area_m2 = 0.0038;
constexpr double g_engine_injector_max_flow_area_m2 = 0.000019;
constexpr double g_engine_piston_max_flow_area_m2 = 0.00304;
constexpr double g_engine_erunner_max_flow_area_m2 = 0.00266;
constexpr double g_engine_eplenum_max_flow_area_m2 = 0.0095;
constexpr double g_engine_exhaust_max_flow_area_m2 = 0.0076;
constexpr double g_engine_piston_0_theta_r = 0.0;
constexpr double g_engine_piston_1_theta_r = 9.42477796077;
constexpr double g_engine_piston_2_theta_r = 3.14159265359;
constexpr double g_engine_piston_3_theta_r = 6.28318530718;
constexpr double g_engine_irunner_valve_engage_r = -1.727875959;
constexpr double g_engine_irunner_valve_ramp_r = 2.51327412287;
constexpr double g_engine_piston_valve_engage_r = 7.696902001;
constexpr double g_engine_piston_valve_ramp_r = 2.51327412287;
constexpr double g_engine_sparkplug_engage_r = 5.969026041;
constexpr double g_engine_sparkplug_on_r = 0.62831853071;
constexpr double g_engine_no_throttle = 0.000;
constexpr double g_engine_low_throttle = 0.020;
constexpr double g_engine_mid_throttle = 0.100;
constexpr double g_engine_high_throttle = 1.0;
constexpr double g_engine_crankshaft_mass_kg = 1.3;
constexpr double g_engine_crankshaft_radius_m = 0.0337;
constexpr double g_engine_flywheel_mass_kg = 3.8;
constexpr double g_engine_flywheel_radius_m = 0.28;
constexpr double g_engine_limiter_cutoff_r_per_s = 900.0;
constexpr double g_engine_limiter_relaxed_r_per_s = 400.0;
constexpr double e_engine_starter_rated_torque_n_m = 90.0;
constexpr double g_engine_starter_no_load_r_per_s = 600.0;
constexpr double g_engine_starter_radius_m = 0.015;

static struct node_s g_engine_node[] = {
    [0] = source_d({1, 21}),
    [1] = throttle_d({2, 14}),
    [2] = irunner_d(g_engine_piston_0_theta_r, {4}),
    [3] = injector_d(2, {4}),
    [4] = piston_d(g_engine_piston_0_theta_r, {5}),
    [5] = erunner_d({18}),
    [6] = irunner_d(g_engine_piston_1_theta_r, {8}),
    [7] = injector_d(6, {8}),
    [8] = piston_d(g_engine_piston_1_theta_r, {9}),
    [9] = erunner_d({18}),
    [10] = irunner_d(g_engine_piston_2_theta_r, {12}),
    [11] = injector_d(10, {12}),
    [12] = piston_d(g_engine_piston_2_theta_r, {13}),
    [13] = erunner_d({18}),
    [14] = irunner_d(g_engine_piston_3_theta_r, {16}),
    [15] = injector_d(14, {16}),
    [16] = piston_d(g_engine_piston_3_theta_r, {17}),
    [17] = erunner_d({18}),
    [18] = eplenum_d(0, {19}),
    [19] = exhaust_d({20}),
    [20] = sink_d(),
    [21] = throttle_d({6, 10}),
};